import { CoreModelsResourceManagementPublishedSchedulePublishingCreatePublishingRequest } from "src/api/models";

export type PublishingRequestBody = CoreModelsResourceManagementPublishedSchedulePublishingCreatePublishingRequest;