import { CoreModelsResourceManagementScheduleGeneratorGeneratePlannedScheduleRequest } from "src/api/models";

export type GeneratePlannedScheduleRequest = NonNullable<CoreModelsResourceManagementScheduleGeneratorGeneratePlannedScheduleRequest>