import { CoreModelsResourceManagementPlannedScheduleCreateOrUpdatePlannedScheduleRequest } from "src/api/models";

export type PlannedScheduleCreateOrUpdateRequestBody = CoreModelsResourceManagementPlannedScheduleCreateOrUpdatePlannedScheduleRequest;