import { CoreModelsResourceManagementPlannedScheduleGetPlannedScheduleByConditionRequest } from "src/api/models";

export type PlannedScheduleRequest = CoreModelsResourceManagementPlannedScheduleGetPlannedScheduleByConditionRequest;