export const dcTableNameList = [
    "DC_DictionaryCategoryDTO",
    "DC_LanguageDTO",
    "DC_CityDTO",
    "DC_CountryDTO",
    "DC_CountyDTO",
    "DC_GenderDTO",
    "DC_PatientIdTypeDTO",
    "DC_AppointmentCancellationDTO",
    "DC_AppointmentStatusDTO",
    "DC_BookingAreaDTO",
    "DC_ClinicRoomStateDTO",
    "DC_ClinicTypeDTO",
    "DC_FloorDTO",
    "DC_CompanyTypeDTO",
    "DC_ContactTypeDTO",
    "DC_DayDTO",
    "DC_DocumentTemplateCategoryDTO",
    "DC_EmailTemplateCategoryDTO",
    "DC_ExamTypeDTO",
    "DC_ExposureFrequencyDTO",
    "DC_ExposureTypeDTO",
    "DC_InvoiceTypeDTO",
    "DC_InvoiceModeDTO",
    "DC_ItemCategoryDTO",
    "DC_ItemConsumerTypeDTO",
    "DC_ItemStatusDTO",
    "DC_ItemTypeDTO",
    "DC_MacroTypeDTO",
    "DC_MarkerDTO",
    "DC_MedicalEmployeeScheduleTypeDTO",
    "DC_MedicalEmployeeTypeDTO",
    "DC_NationalityDTO",
    "DC_OccupationalHealthClassificationDTO",
    "DC_OccupationalHealthPriceCategoryDTO",
    "DC_OccupationalHealthTypeDTO",
    "DC_PartnerModeDTO",
    "DC_PartnerTypeDTO",
    "DC_PatientAddressTypeDTO",
    "DC_PriceTableStatusDTO",
    "DC_PublicPlaceCategoryDTO",
    "DC_SamplingItemDTO",
    "DC_ScheduleSpecialTypeDTO",
    "DC_ScheduleTemplateCopyTypeDTO",
    "DC_ServiceCategoryDTO",
    "DC_ServicePackageCategoryDTO",
    "DC_ServiceTypeDTO",
    "DC_SubServicePackageCategoryDTO",
    "DC_SubServicePackageTypeDTO",
    "DC_TitleTypeDTO",
    "DC_TwoFactorAuthenticationTypeDTO",
    "DC_UserStatusDTO",
    "DC_UserTypeDTO",
    "DC_VIPDTO",
    "DC_WeekTypeDTO",
    "DC_CurrencyDTO",
    "DC_EInvoiceTypeDTO",
    "DC_InvoiceBusinessCategoryDTO",
    "DC_InvoiceIdentificationTypeDTO",
    "DC_InvoicePartnerCategoryDTO",
    "DC_ItemUnitDTO",
    "DC_PaymentMethodDTO",
    "DC_ClinicInventoryItemStatusDTO",
    "DC_ScheduleWarningDTO",
    "DC_CancellationStatusDTO",
    "DC_PatientIdTypeCategoryDTO",
    "DC_StatusDTO",
    "DC_ItemProcurationalCategoryDTO",
    "DC_LabRepeatPeriodDTO",
    "DC_LabSamplingTypeDTO",
    "DC_LabProviderDTO",
    "DC_ServicePackageTypeDTO",
    "DC_AppointmentCartStatusDTO",
    "DC_ContractStatusDTO",
    "DC_ContractTypeDTO",
    "DC_ContractServiceTypeDTO",
    "DC_ContractPriceModeDTO",
    "DC_ContractTemplateTypeDTO",
    "DC_ContractTemplateNameDTO",
    "DC_SubContractNumberTypeDTO",
    "DC_EventActivationDTO",
    "DC_EventFrequencyDTO",
    "DC_ContractEventDTO",
    "DC_ContractPriceTypeDTO",
    "DC_TurnoverDayTypeDTO",
    "DC_InvoiceIssueTypeDTO",
    "DC_DayNumberDTO",
    "DC_MonthDTO",
    "DC_ContractPaymentTypeDTO",
    "DC_InvoiceCustomerTypeDTO",
    "DC_PayerTypeDTO",
    "DC_AdditionalCostUnitDTO",
    "DC_AdditionalCostDTO",
    "DC_WorkLoadPeriodTypeDTO",
    "DC_DistributionTypeDTO",
    "NEHI_AmbulantProvisionTypeDTO",
    "NEHI_AmbulantReleaseTypeDTO",
    "NEHI_PatientReleaseTypeDTO",
    "NEHI_ProvisionTypeDTO",
    "NEHI_EPROGroupDTO",
    "NEHI_EPROTypeDTO",
    "NEHI_EventTypeDTO",
    "NEHI_ErrorMessageSeverityDTO",
    "DC_ContractCardNameDTO",
    "DC_ContractCardType",
    "DC_QuotationStatusDTO",
    "DC_SubQuotationNumberTypeDTO",
    "DC_SubQuotationNumberServiceTypeDTO",
    "DC_InvocationDTO",
] as const;

type ExtractDcTableBaseName<T extends DcTableName> = T extends `${infer DcTableBaseName}DTO` ? DcTableBaseName : T;
type CapitalizeInReverse<T, Pre extends string = ""> = T extends `${infer FirstLetter}${infer Rest}`
    ? Rest extends ""
        ? `${Lowercase<Pre>}${Uppercase<FirstLetter>}`
        : CapitalizeInReverse<Rest, `${Pre}${FirstLetter}`>
    : T
type ExtractDcTableBasePropertyName<T extends DcTableBaseName> = T extends `${infer PreString}_${infer RestString}`
    ? `${CapitalizeInReverse<PreString>}_${RestString}`
    : never;

export type DcTableName = typeof dcTableNameList[number];
export type DcTableBaseName = ExtractDcTableBaseName<DcTableName>;
export type DcTableBasePropertyName = ExtractDcTableBasePropertyName<DcTableBaseName>;
export type DcTableIdPropertyName = `${DcTableBasePropertyName}Id`;
export type DcTableInitPagePropertyName = `${DcTableBasePropertyName}List`;
