import { Component } from '@angular/core';
import { ASSISTANTS_ROUTE, AUTHORITIES_ROUTE, CITIES_ROUTE, CLINICS_ROUTE, CONFIGURATIONS_ROUTE, DICTIONARY_ENTRIES_ROUTE, DIVISION_NUMBERS_ROUTE, DOCTORS_ROUTE, DOCUMENT_TEMPLATES_ROUTE, EMAIL_TEMPLATES_ROUTE, EXPOSURES_ROUTE, FEOR_GROUP_ROUTE, FUNCTIONS_ROUTE, ITEMS_ROUTE, JOB_TITLE_ROUTE, LABS_ROUTE, MASTER_DATA_BASE_ROUTE, PARTNERS_ROUTE, PATIENTS_ROUTE, PRICE_TABLES_ROUTE, ROLES_ROUTE, SCHEDULE_BASE_ROUTE, SCHEDULE_GENERATOR, SCHEDULE_PLANNER, SCHEDULE_PUBLISHING, SCHEDULE_TEMPLATE, SERVICES_ROUTE, SERVICE_PACKAGES_ROUTE, SERVICE_PROVIDER_ENTITIES_ROUTE, SERVICE_SUB_PACKAGES_ROUTE, SYSTEM_BASE_ROUTE, USERS_ROUTE, MEDICAL_MANAGEMENT_BASE_ROUTE, RECEPTION_ROUTE, CC_BASE_ROUTE, CC_APPOINTMENTS_ROUTE } from "../../../../../app.config";


@Component({
    selector: 'app-sidebar-menu',
    templateUrl: './sidebar-menu.component.html',
    styleUrls: ['./sidebar-menu.component.scss'],
})
export class SidebarMenuComponent {
    constants = {
        MASTER_DATA_BASE_ROUTE: MASTER_DATA_BASE_ROUTE,
        SERVICES_ROUTE: SERVICES_ROUTE,
        SERVICE_SUB_PACKAGES_ROUTE: SERVICE_SUB_PACKAGES_ROUTE,
        SERVICE_PACKAGES_ROUTE: SERVICE_PACKAGES_ROUTE,
        PRICE_TABLES_ROUTE: PRICE_TABLES_ROUTE,
        ITEMS_ROUTE: ITEMS_ROUTE,
        PATIENTS_ROUTE: PATIENTS_ROUTE,
        PARTNERS_ROUTE: PARTNERS_ROUTE,
        DICTIONARY_ENTRIES_ROUTE: DICTIONARY_ENTRIES_ROUTE,
        DOCUMENT_TEMPLATES_ROUTE: DOCUMENT_TEMPLATES_ROUTE,
        EMAIL_TEMPLATES_ROUTE: EMAIL_TEMPLATES_ROUTE,
        SERVICE_PROVIDER_ENTITIES_ROUTE: SERVICE_PROVIDER_ENTITIES_ROUTE,
        LABS_ROUTE: LABS_ROUTE,
        CITIES_ROUTE: CITIES_ROUTE,
        CLINICS_ROUTE: CLINICS_ROUTE,
        DOCTORS_ROUTE: DOCTORS_ROUTE,
        ASSISTANTS_ROUTE: ASSISTANTS_ROUTE,
        EXPOSURES_ROUTE: EXPOSURES_ROUTE,
        FEOR_GROUP_ROUTE: FEOR_GROUP_ROUTE,
        JOB_TITLE_ROUTE: JOB_TITLE_ROUTE,
        // TODO partner specifikus expozíciós mátrix... : export const TODO_ROUTE: string = "TODO";

        SCHEDULE_BASE_ROUTE: SCHEDULE_BASE_ROUTE,
        SCHEDULE_TEMPLATE: SCHEDULE_TEMPLATE,
        SCHEDULE_PLANNER: SCHEDULE_PLANNER,
        SCHEDULE_GENERATOR: SCHEDULE_GENERATOR,
        SCHEDULE_PUBLISHING: SCHEDULE_PUBLISHING,

        CC_BASE_ROUTE: CC_BASE_ROUTE,
        CC_APPOINTMENTS_ROUTE: CC_APPOINTMENTS_ROUTE,

        SYSTEM_BASE_ROUTE: SYSTEM_BASE_ROUTE,
        USERS_ROUTE: USERS_ROUTE,
        ROLES_ROUTE: ROLES_ROUTE,
        AUTHORITIES_ROUTE: AUTHORITIES_ROUTE,
        FUNCTIONS_ROUTE: FUNCTIONS_ROUTE,
        CONFIGURATIONS_ROUTE: CONFIGURATIONS_ROUTE,
        DIVISION_NUMBERS_ROUTE: DIVISION_NUMBERS_ROUTE,

        MEDICAL_MANAGEMENT_BASE_ROUTE: MEDICAL_MANAGEMENT_BASE_ROUTE,
        RECEPTION_ROUTE: RECEPTION_ROUTE,
    }
}
